### ISSUE TITLE
IPtoCompany plugin not working

### ISSUE THREAD

**Issue by robles-design** [Romain/Matomo-IP-to-Company#1]
I have installed the IPtoCompany plugin and get these two warnings:

```
WARNING: Sorting the API method &quot;Live.getLastVisitDetails&quot; by column is currently not supported. To avoid this warning remove the URL parameter &quot;filter_sort_column&quot; from your API request. (Module: API, Action: getCompanies, Method: Live.getLastVisitsDetails, In CLI mode: false)

WARNING: /piwik/plugins/IPtoCompany/API.php(53): Warning - gethostbyaddr(): Address is not a valid IPv4 or IPv6 address - Matomo 3.13.1-b2 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: IPtoCompany, Action: getCompanies, Method: IPtoCompany.getCompanies, In CLI mode: false)
```

Matomo-Version: 3.13.1-b2
MySQL-Version: 5.7.28-nmm1-log
PHP-Version: 7.3.11-nmm1

**Comment by Romain** [comment]
Hi @robles-design ,

Thanks for reporting this.
Second warning is due to the fact that the API call didn't work (first warning).
I pushed a new version disabling the `filter_sort_column` which seems to be causing the problem. Let me know if this solved the problem for you.

Romain

**Comment by robles-design** [comment]
Hi @Romain,

I've updated the plugin and get still warnings:

```
WARNING: Sorting the API method &quot;Live.getLastVisitDetails&quot; by column is currently not supported. To avoid this warning remove the URL parameter &quot;filter_sort_column&quot; from your API request. (Module: API, Action: getCompanies, Method: Live.getLastVisitsDetails, In CLI mode: false)

WARNING: /piwik/plugins/IPtoCompany/API.php(53): Warning - gethostbyaddr(): Address is not a valid IPv4 or IPv6 address - Matomo 3.13.1-b2 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: IPtoCompany, Action: getCompanies, Method: IPtoCompany.getCompanies, In CLI mode: false)
```

**Comment by Romain** [comment]
Hmmm... This is weird. 
Is it preventing the plugin from completely working?

I'm not using it anymore. However, it seems that it has been [disabled in the core of Matomo](https://github.com/matomo-org/matomo/blob/5ae8668181ff6e622a290df6321c006ef30284e1/plugins/Live/API.php#L187).

I don't understand why you get this error since I don't pass this parameter in [my request](https://github.com/Romain/Matomo-IP-to-Company/blob/b10331d3d6a71aeffaf0b16d94a04648c381ff7b/API.php#L34).

Perhaps could someone from @matomo help here? @tsteur @mattab ?

**Comment by robles-design** [comment]
Yes, the plugin is not working. There is no entry in the companies section in any of my tracked domains.

**Comment by Romain** [comment]
Ok. I guess that you have traffic on your sites and that there's no reason for it to not work.

**Comment by robles-design** [comment]
Yes, I have traffic on the sites and the other stats are working.

**Comment by robles-design** [comment]
@Romain what the heck have you done? I saw a plugin update of IPtoCompany in the admin panel, did the update and now Matomo isn't working any more!!!

[Zend_Db_Statement_Exception]  
SQLSTATE[42S02]: Base table or view not found: 1051 Unknown table 'xyz_ip_to_company'

**Comment by robles-design** [comment]
I deleted the plugin and Matomo is working again.

**Comment by Romain** [comment]
@robles-design, I updated it with the ability to plug it into [IPInfo.io](https://ipinfo.io/) to get more accurate and readable results. It seems that the process to create the table during a plugin update is not fully workable yet. If you reinstall it you won't have any problem since it creates the table without any problem on install, not on update. Results will also be better.

I'm still new to plugin development on Matomo. I'm not sure how to make this migration run smoothly on plugin update. I need to figure this out.

**Comment by robles-design** [comment]
Sorry, I will not reinstall it in the near future, because the plugin isn't working on my system, crashed it and the ability to plug it into IPInfo.io will not fix the errors I got before. So it will still not work on my system and the risk of a completely not working Matomo installation is to high, because I have clients and no time for experiments. Maybe later  this month.

**Comment by Romain** [comment]
@robles-design No problem, I understand. I'm sorry for these hickups.
As I mentioned before, the warnings that you had were very likely related to a function of Matomo that I used and not directly to this plugin.
The crash that you experienced was my fault though and it should be resolved now.
My point is not to experiment, but to deliver a fully functional plugin. I'm doing it for my own use, in a professional context too, but I'm still new to Matomo plugin development and there are some concepts of Matomo that I still don't completely manage. It should be more stable in the next few weeks.
Thanks anyway for trying and reporting this.
